"""fix_reservation_race_condition

Revision ID: e414c8568410
Revises: 001
Create Date: 2026-02-15 22:30:09.717709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e414c8568410'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contributions', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('contributions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reservations', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('reservations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint('uq_reservation_item_id', 'reservations', ['item_id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('wishlist_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('wishlists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('wishlist_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('uq_reservation_item_id', 'reservations', type_='unique')
    op.alter_column('reservations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reservations', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('contributions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contributions', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
